### ISSUE TITLE
Preventing Accidental Triggering of Emoji Panel Near Bottom of Issue

### ISSUE THREAD

**Issue by Leizhenpeng** [axolo-co/github-emoji-commenter-extension#2]
## Description
We aim to refine the positioning of issue titles to mitigate the frequent occurrence of accidental activation of the emoji panel when hovering near the bottom. 

This improvement ensures a smoother user experience by reducing inadvertent interactions while navigating through issues.

## Suggestion
1. Add debounce ，the emoji panel will be triggered after a delay of 1000ms when moving the new line

2. Change the pop-up position to the beginning of the line

**Comment by cosydney** [comment]
Makes sense thank you
