### ISSUE TITLE
Comments cannot be contacted on the same page, must be refreshed

### ISSUE THREAD

**Issue by Leizhenpeng** [axolo-co/github-emoji-commenter-extension#3]
# problem
If u don't refresh web page , you can only comment at most once on the same page, and subsequent comments will fail~

# suggestion
some capture can help us find problem

When commenting continuously, there are multiple Textarea whose ID does not start with new_inline.

![image](https://github.com/axolo-co/Emoji-reactions-for-GitHub/assets/50035229/bbcfd788-e439-402a-ac02-044999ae6043)

**Comment by cosydney** [comment]
Thank you I've pushed the new version you proposed
